CREATE TABLE [dbo].[tblItems]
(
[StockSite] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[ItemID] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[ItemNumber] [bigint] NULL,
[OriginalSite] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[ProductCode] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[LotName] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[LotCode] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[ProductionDate] [datetime] NULL,
[UseByDate] [datetime] NULL,
[ItemRegtime] [datetime] NULL,
[XactRegtime] [datetime] NULL,
[DeviceName] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Employee] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[ItemInventory] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[ItemInventoryLocation] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[ProductDescription] [nvarchar] (80) COLLATE Latin1_General_CI_AS NULL,
[NominalWeight] [decimal] (18, 2) NULL,
[RegistrationTime] [datetime] NULL,
[WeekNo] [int] NULL,
[Part] [nvarchar] (5) COLLATE Latin1_General_CI_AS NULL,
[KillNo] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[ManualKillNo] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[ParentItem] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[YieldGroup] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[OriginalWeight] [decimal] (18, 2) NULL,
[ItemNominal] [decimal] (18, 2) NULL,
[ItemWeight] [decimal] (18, 2) NULL,
[XactWeight] [decimal] (18, 2) NULL,
[ItemTare] [decimal] (18, 2) NULL,
[ItemRtype] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[XactRtype] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Xactpath] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Batch] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[ToLotCode] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[ToLotName] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[ExternalCode] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[BoningHallLotId] [int] NULL,
[XactItem] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[XactPack] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[XactProductionDate] [datetime] NULL,
[XactPathDescription] [nvarchar] (100) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
